
variables:
    CONAN_USERNAME: "dvd"
    CONAN_REFERENCE: "libigl/git"
    CONAN_CHANNEL: "testing"
    CONAN_LOGIN_USERNAME: "dvd"
    CONAN_USER_HOME: "$CI_PROJECT_DIR/.conan"

.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan_package_tools
        - conan user
    script:
        - python build.py

stages:
    - header_only
    - static_build
    - upload

# gcc-4.9:
    # image: conanio/gcc49
    # variables:
    #     CONAN_GCC_VERSIONS: "4.9"
    # <<: *build-template

# gcc-5:
    # image: conanio/gcc5
    # variables:
    #     CONAN_GCC_VERSIONS: "5"
    # <<: *build-template

# gcc-6:
    # image: conanio/gcc6
    # variables:
    #     CONAN_GCC_VERSIONS: "6"
    # <<: *build-template

# gcc-7:
    # image: conanio/gcc7
    # variables:
    #     CONAN_GCC_VERSIONS: "7"
    # <<: *build-template

gcc-8:header_only:
    image: conanio/gcc8
    stage: header_only
    artifacts:
      paths:
        - .conan
      expire_in: 1 day
    variables:
        CONAN_GCC_VERSIONS: "8"
        PACKAGE_BUILD_STATIC_LIB: "0"
    <<: *build-template

gcc-8:build0:
    image: conanio/gcc8
    stage: static_build
    artifacts:
      paths:
        - .conan
      expire_in: 1 day
    variables:
        CONAN_GCC_VERSIONS: "8"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "1"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-8:header_only
    <<: *build-template

# gcc-8:build1:
#     image: conanio/gcc8
#     stage: static_build
#     artifacts:
#         paths:
#             - .conan
#     variables:
#         CONAN_GCC_VERSIONS: "8"
#         CONAN_TOTAL_PAGES: "6"
#         CONAN_CURRENT_PAGE: "2"
#         PACKAGE_BUILD_STATIC_LIB: "1"
#     dependencies:
#         - gcc-8:header_only
#     <<: *build-template

# gcc-8:build2:
#     image: conanio/gcc8
#     stage: static_build
#     artifacts:
#         paths:
#             - .conan
#     variables:
#         CONAN_GCC_VERSIONS: "8"
#         CONAN_TOTAL_PAGES: "6"
#         CONAN_CURRENT_PAGE: "3"
#         PACKAGE_BUILD_STATIC_LIB: "1"
#     dependencies:
#         - gcc-8:header_only
#     <<: *build-template

# gcc-8:build3:
#     image: conanio/gcc8
#     stage: static_build
#     artifacts:
#         paths:
#             - .conan
#     variables:
#         CONAN_GCC_VERSIONS: "8"
#         CONAN_TOTAL_PAGES: "6"
#         CONAN_CURRENT_PAGE: "4"
#         PACKAGE_BUILD_STATIC_LIB: "1"
#     dependencies:
#         - gcc-8:header_only
#     <<: *build-template

# gcc-8:build4:
#     image: conanio/gcc8
#     stage: static_build
#     artifacts:
#         paths:
#             - .conan
#     variables:
#         CONAN_GCC_VERSIONS: "8"
#         CONAN_TOTAL_PAGES: "6"
#         CONAN_CURRENT_PAGE: "5"
#         PACKAGE_BUILD_STATIC_LIB: "1"
#     dependencies:
#         - gcc-8:header_only
#     <<: *build-template

# gcc-8:build5:
#     image: conanio/gcc8
#     stage: static_build
#     artifacts:
#         paths:
#             - .conan
#     variables:
#         CONAN_GCC_VERSIONS: "8"
#         CONAN_TOTAL_PAGES: "6"
#         CONAN_CURRENT_PAGE: "6"
#         PACKAGE_BUILD_STATIC_LIB: "1"
#     dependencies:
#         - gcc-8:header_only
#     <<: *build-template

# clang-3.9:
#     image: conanio/clang39
#     variables:
#         CONAN_CLANG_VERSIONS: "3.9"
#     <<: *build-template

# clang-4.0:
#     image: conanio/clang40
#     variables:
#         CONAN_CLANG_VERSIONS: "4.0"
#     <<: *build-template

# clang-5.0:
#     image: conanio/clang50
#     variables:
#         CONAN_CLANG_VERSIONS: "5.0"
#     <<: *build-template

# clang-6.0:
#     image: conanio/clang60
#     variables:
#         CONAN_CLANG_VERSIONS: "6.0"
#     <<: *build-template

# clang-7.0:
#     image: conanio/clang7
#     variables:
#         CONAN_CLANG_VERSIONS: "7.0"
#     <<: *build-template

upload:
    image: conanio/gcc8
    stage: upload
    script:
        - conan
        - conan search
        - conan search libigl/git@dvd/stable
    artifacts:
      paths:
        - .conan
      expire_in: 1 day
    dependencies:
        - gcc-8:build0
        # - gcc-8:build1
        # - gcc-8:build2
        # - gcc-8:build3
        # - gcc-8:build4
        # - gcc-8:build5
