
variables:
    CONAN_USERNAME: "dvd"
    CONAN_CHANNEL: "testing"
    CONAN_LOGIN_USERNAME: "dvd"

stages:
  - header_only
  - static_build

.build-template: &build-template
  before_script:
    - sudo pip install --upgrade conan_package_tools
    - conan user
  script:
    - python build.py
    - ./scripts/upload_to_bintray $CI_COMMIT_REF_NAME

gcc-8:header_only:
  image: conanio/gcc8
  stage: header_only
  variables:
    CONAN_GCC_VERSIONS: "8"
    PACKAGE_BUILD_STATIC_LIB: "0"
  <<: *build-template

gcc-8:build1:
    image: conanio/gcc8
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "8"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "1"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-8:header_only
    <<: *build-template

gcc-8:build2:
    image: conanio/gcc8
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "8"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "2"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-8:header_only
    <<: *build-template

gcc-8:build3:
    image: conanio/gcc8
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "8"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "3"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-8:header_only
    <<: *build-template

gcc-8:build4:
    image: conanio/gcc8
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "8"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "4"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-8:header_only
    <<: *build-template

gcc-8:build5:
    image: conanio/gcc8
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "8"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "5"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-8:header_only
    <<: *build-template

gcc-8:build6:
    image: conanio/gcc8
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "8"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "6"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-8:header_only
    <<: *build-template

gcc-7:header_only:
  image: conanio/gcc7
  stage: header_only
  variables:
    CONAN_GCC_VERSIONS: "7"
    PACKAGE_BUILD_STATIC_LIB: "0"
  <<: *build-template

gcc-7:build1:
    image: conanio/gcc7
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "7"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "1"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-7:header_only
    <<: *build-template

gcc-7:build2:
    image: conanio/gcc7
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "7"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "2"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-7:header_only
    <<: *build-template

gcc-7:build3:
    image: conanio/gcc7
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "7"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "3"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-7:header_only
    <<: *build-template

gcc-7:build4:
    image: conanio/gcc7
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "7"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "4"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-7:header_only
    <<: *build-template

gcc-7:build5:
    image: conanio/gcc7
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "7"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "5"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-7:header_only
    <<: *build-template

gcc-7:build6:
    image: conanio/gcc7
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "7"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "6"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-7:header_only
    <<: *build-template

gcc-6:header_only:
  image: conanio/gcc6
  stage: header_only
  variables:
    CONAN_GCC_VERSIONS: "6"
    PACKAGE_BUILD_STATIC_LIB: "0"
  <<: *build-template

gcc-6:build1:
    image: conanio/gcc6
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "6"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "1"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-6:header_only
    <<: *build-template

gcc-6:build2:
    image: conanio/gcc6
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "6"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "2"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-6:header_only
    <<: *build-template

gcc-6:build3:
    image: conanio/gcc6
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "6"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "3"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-6:header_only
    <<: *build-template

gcc-6:build4:
    image: conanio/gcc6
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "6"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "4"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-6:header_only
    <<: *build-template

gcc-6:build5:
    image: conanio/gcc6
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "6"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "5"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-6:header_only
    <<: *build-template

gcc-6:build6:
    image: conanio/gcc6
    stage: static_build
    variables:
        CONAN_GCC_VERSIONS: "6"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "6"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - gcc-6:header_only
    <<: *build-template

clang-7.0:header_only:
  image: conanio/clang7
  stage: header_only
  variables:
    CONAN_CLANG_VERSIONS: "7.0"
    PACKAGE_BUILD_STATIC_LIB: "0"
  <<: *build-template

clang-7.0:build1:
    image: conanio/clang7
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "7.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "1"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-7.0:header_only
    <<: *build-template

clang-7.0:build2:
    image: conanio/clang7
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "7.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "2"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-7.0:header_only
    <<: *build-template

clang-7.0:build3:
    image: conanio/clang7
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "7.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "3"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-7.0:header_only
    <<: *build-template

clang-7.0:build4:
    image: conanio/clang7
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "7.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "4"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-7.0:header_only
    <<: *build-template

clang-7.0:build5:
    image: conanio/clang7
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "7.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "5"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-7.0:header_only
    <<: *build-template

clang-7.0:build6:
    image: conanio/clang7
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "7.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "6"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-7.0:header_only
    <<: *build-template

clang-6.0:header_only:
  image: conanio/clang60
  stage: header_only
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
    PACKAGE_BUILD_STATIC_LIB: "0"
  <<: *build-template

clang-6.0:build1:
    image: conanio/clang60
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "1"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-6.0:header_only
    <<: *build-template

clang-6.0:build2:
    image: conanio/clang60
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "2"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-6.0:header_only
    <<: *build-template

clang-6.0:build3:
    image: conanio/clang60
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "3"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-6.0:header_only
    <<: *build-template

clang-6.0:build4:
    image: conanio/clang60
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "4"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-6.0:header_only
    <<: *build-template

clang-6.0:build5:
    image: conanio/clang60
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "5"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-6.0:header_only
    <<: *build-template

clang-6.0:build6:
    image: conanio/clang60
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "6"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-6.0:header_only
    <<: *build-template

clang-5.0:header_only:
  image: conanio/clang50
  stage: header_only
  variables:
    CONAN_CLANG_VERSIONS: "5.0"
    PACKAGE_BUILD_STATIC_LIB: "0"
  <<: *build-template

clang-5.0:build1:
    image: conanio/clang50
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "1"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-5.0:header_only
    <<: *build-template

clang-5.0:build2:
    image: conanio/clang50
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "2"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-5.0:header_only
    <<: *build-template

clang-5.0:build3:
    image: conanio/clang50
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "3"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-5.0:header_only
    <<: *build-template

clang-5.0:build4:
    image: conanio/clang50
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "4"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-5.0:header_only
    <<: *build-template

clang-5.0:build5:
    image: conanio/clang50
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "5"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-5.0:header_only
    <<: *build-template

clang-5.0:build6:
    image: conanio/clang50
    stage: static_build
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
        CONAN_TOTAL_PAGES: "6"
        CONAN_CURRENT_PAGE: "6"
        PACKAGE_BUILD_STATIC_LIB: "1"
    dependencies:
        - clang-5.0:header_only
    <<: *build-template
